/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: e:\compi\revista\sliders1.dat */
/* Date: Mon May 17 17:39:41 1999 */
/* Do not hand edit! */

#define FOTO_BEOS1                       0        /* BMP  */
#define FOTO_BEOS2                       1        /* BMP  */
#define FOTO_BEOS3                       2        /* BMP  */
#define FOTO_C1                          3        /* BMP  */
#define FOTO_COVOX1                      4        /* BMP  */
#define FOTO_COVOX2                      5        /* BMP  */
#define FOTO_COVOX3                      6        /* BMP  */
#define FOTO_DARKBASIC1                  7        /* BMP  */
#define FOTO_DARKBASIC2                  8        /* BMP  */
#define FOTO_DELABU1                     9        /* BMP  */
#define FOTO_DELABU2                     10       /* BMP  */
#define FOTO_DELABU3                     11       /* BMP  */
#define FOTO_DELABU4                     12       /* BMP  */
#define FOTO_DELABU5                     13       /* BMP  */
#define FOTO_DURANGO1                    14       /* BMP  */
#define FOTO_DURANGO2                    15       /* BMP  */
#define FOTO_DURANGO3                    16       /* BMP  */
#define FOTO_DURANGO4                    17       /* BMP  */
#define FOTO_ENTREVISTABEOS              18       /* BMP  */
#define FOTO_FREEDOS1                    19       /* BMP  */
#define FOTO_FREEDOS2                    20       /* BMP  */
#define FOTO_GAMEBOY1                    21       /* BMP  */
#define FOTO_GAMEBOY2                    22       /* BMP  */
#define FOTO_GAMEBOY3                    23       /* BMP  */
#define FOTO_LINUX1                      24       /* BMP  */
#define FOTO_LINUX2                      25       /* BMP  */
#define FOTO_MACOS                       26       /* BMP  */
#define FOTO_MEKKA1                      27       /* BMP  */
#define FOTO_MEKKA2                      28       /* BMP  */
#define FOTO_MEKKA3                      29       /* BMP  */
#define FOTO_MEKKA4                      30       /* BMP  */
#define FOTO_MEKKA5                      31       /* BMP  */
#define FOTO_MEKKA6                      32       /* BMP  */
#define FOTO_MEKKA7                      33       /* BMP  */
#define FOTO_MEKKA8                      34       /* BMP  */
#define FOTO_OVERCLOCKING1               35       /* BMP  */
#define FOTO_OVERCLOCKING2               36       /* BMP  */
#define FOTO_OVERCLOCKING3               37       /* BMP  */
#define FOTO_PROGRAMACIONGRAFICA1        38       /* BMP  */
#define FOTO_PROGRAMACIONGRAFICA2        39       /* BMP  */
#define FOTO_RADIOPACKET1                40       /* BMP  */
#define FOTO_RADIOPACKET2                41       /* BMP  */
#define FOTO_REVISTA1                    42       /* BMP  */
#define FOTO_REVISTA2                    43       /* BMP  */
#define FOTO_REVISTA3                    44       /* BMP  */
#define FOTO_REVISTA4                    45       /* BMP  */
#define FOTO_SCENE1                      46       /* BMP  */
#define FOTO_SCENE2                      47       /* BMP  */
#define FOTO_SCENE3                      48       /* BMP  */
#define FOTO_SDL1                        49       /* BMP  */
#define FOTO_SDL2                        50       /* BMP  */
#define PAL_ENTREVISTABEOS               51       /* PAL  */
#define PALETA_BEOS1                     52       /* PAL  */
#define PALETA_BEOS2                     53       /* PAL  */
#define PALETA_BEOS3                     54       /* PAL  */
#define PALETA_C1                        55       /* PAL  */
#define PALETA_COVOX1                    56       /* PAL  */
#define PALETA_COVOX2                    57       /* PAL  */
#define PALETA_COVOX3                    58       /* PAL  */
#define PALETA_DARKBASIC1                59       /* PAL  */
#define PALETA_DARKBASIC2                60       /* PAL  */
#define PALETA_DELABU1                   61       /* PAL  */
#define PALETA_DELABU2                   62       /* PAL  */
#define PALETA_DELABU3                   63       /* PAL  */
#define PALETA_DELABU4                   64       /* PAL  */
#define PALETA_DELABU5                   65       /* PAL  */
#define PALETA_DURANGO1                  66       /* PAL  */
#define PALETA_DURANGO2                  67       /* PAL  */
#define PALETA_DURANGO3                  68       /* PAL  */
#define PALETA_DURANGO4                  69       /* PAL  */
#define PALETA_FREEDOS1                  70       /* PAL  */
#define PALETA_FREEDOS2                  71       /* PAL  */
#define PALETA_GAMEBOY1                  72       /* PAL  */
#define PALETA_GAMEBOY2                  73       /* PAL  */
#define PALETA_GAMEBOY3                  74       /* PAL  */
#define PALETA_LINUX1                    75       /* PAL  */
#define PALETA_LINUX2                    76       /* PAL  */
#define PALETA_MACOS                     77       /* PAL  */
#define PALETA_MEKKA1                    78       /* PAL  */
#define PALETA_MEKKA2                    79       /* PAL  */
#define PALETA_MEKKA3                    80       /* PAL  */
#define PALETA_MEKKA4                    81       /* PAL  */
#define PALETA_MEKKA5                    82       /* PAL  */
#define PALETA_MEKKA6                    83       /* PAL  */
#define PALETA_MEKKA7                    84       /* PAL  */
#define PALETA_MEKKA8                    85       /* PAL  */
#define PALETA_OVERCLOCKING1             86       /* PAL  */
#define PALETA_OVERCLOCKING2             87       /* PAL  */
#define PALETA_OVERCLOCKING3             88       /* PAL  */
#define PALETA_PROGRAMACIONGRAFICA1      89       /* PAL  */
#define PALETA_PROGRAMACIONGRAFICA2      90       /* PAL  */
#define PALETA_RADIOPACKET1              91       /* PAL  */
#define PALETA_RADIOPACKET2              92       /* PAL  */
#define PALETA_REVISTA1                  93       /* PAL  */
#define PALETA_REVISTA2                  94       /* PAL  */
#define PALETA_REVISTA3                  95       /* PAL  */
#define PALETA_REVISTA4                  96       /* PAL  */
#define PALETA_SCENE1                    97       /* PAL  */
#define PALETA_SCENE2                    98       /* PAL  */
#define PALETA_SCENE3                    99       /* PAL  */
#define PALETA_SDL1                      100      /* PAL  */
#define PALETA_SDL2                      101      /* PAL  */
#define TEXTO_BEOS                       102      /* DATA */
#define TEXTO_C                          103      /* DATA */
#define TEXTO_COVOX                      104      /* DATA */
#define TEXTO_DARKBASIC                  105      /* DATA */
#define TEXTO_DELABU                     106      /* DATA */
#define TEXTO_DURANGO                    107      /* DATA */
#define TEXTO_ENTREVISTABEOS             108      /* DATA */
#define TEXTO_FREEDOS                    109      /* DATA */
#define TEXTO_GAMEBOY                    110      /* DATA */
#define TEXTO_HISTORIA                   111      /* DATA */
#define TEXTO_LINUX                      112      /* DATA */
#define TEXTO_MACOS                      113      /* DATA */
#define TEXTO_MEKKA                      114      /* DATA */
#define TEXTO_OVERCLOCKING               115      /* DATA */
#define TEXTO_PASCAL                     116      /* DATA */
#define TEXTO_PROGRAMACIONGRAFICA        117      /* DATA */
#define TEXTO_RADIOPACKET                118      /* DATA */
#define TEXTO_REVISTA                    119      /* DATA */
#define TEXTO_SCENE                      120      /* DATA */
#define TEXTO_SDL                        121      /* DATA */

